name: Build Tauri Apps (Windows, Linux, macOS)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - platform: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - platform: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - platform: macos-latest
          - platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libglib2.0-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Create GitHub Release (tag builds)
        if: startsWith(github.ref, 'refs/tags/')
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          generateReleaseNotes: true

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseId: ${{ steps.create-release.outputs.id }}
          projectPath: '.'
          tauriScript: 'pnpm tauri'
          args: ${{ matrix.platform == 'ubuntu-latest' && matrix.target != '' && format('--bundles deb,appimage,app --target {0}', matrix.target) || '' }}
          useCross: ${{ matrix.platform == 'ubuntu-latest' && matrix.target != '' }}

      - name: Upload Linux tar.gz artifact to Release
        if: matrix.platform == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/target/${{ matrix.target }}/release/bundle/app/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
